name = "persevero"
version = "1.1.2"

description = "Execute fallible operations multiple times."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "persevero" }

[dependencies]
bigben = ">= 1.0.0 and < 3.0.0"
gleam_erlang = ">= 0.33.0 and < 2.0.0"
gleam_stdlib = ">= 0.52.0 and < 1.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
