name = "retry"
version = "0.1.0"

description = "Gleam functions to rerun code that can fail."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "retry" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
